version: '3.8'

services:
  bfc-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bfc-api-server
    network_mode: host
    environment:
      - NODE_ENV=production
      - PORT=9191
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
